### PR TITLE
updated bignum, nodeunit dependencies

### PR DESCRIPTION
**Pull request by mattstyles**
All the tests pass! 

Fixes 0.12 and 1.x installs.

### CODE REVIEW

**Comment by edimoldovan** [comment]
@fritzy Could you please merge this? Please, please :)

**Comment by fritzy** [comment]
Sorry about the delay! Would either of you like commit commit access?

**Comment by edimoldovan** [comment]
No worries, man. Thanks!
Currently I am using Dulcimer extensively so I’d be happy to help in the future.

**Comment by mattstyles** [comment]
Yeah, I'd also be happy to help, although how much help I would be is highly debateable... :+1:

**Pull request merged**
